<a href="https://colab.research.google.com/github/janviishere/Python-Program/blob/main/python_workshop(day_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
print("My array:", array)
print("Type of array:", type(array))
print("No of dimensions:",  array.ndim)
print("Array Dimensions:", array.shape)
print("No of elements in array:", array.size)

My array: [1 2 3 4 5 6 7 8 9]
Type of array: <class 'numpy.ndarray'>
No of dimensions: 1
Array Dimensions: (9,)
No of elements in array: 9


In [ ]:
array2 = np.array([["janvi",18],["gupta",19]])

In [ ]:
print("My array:", array2)
print("Type of array:", type(array2))
print("No of dimensions:",  array2.ndim)
print("Array Dimensions:", array2.shape)
print("No of elements in array:", array2.size)

My array: [['janvi' '18']
 ['gupta' '19']]
Type of array: <class 'numpy.ndarray'>
No of dimensions: 2
Array Dimensions: (2, 2)
No of elements in array: 4


In [ ]:
l = [1,2,3,4,5,6,7,8,9]
array3 = np.array(l)

In [ ]:
print("My array:", array3)
print("Type of array:", type(array3))
print("No of dimensions:",  array3.ndim)
print("Array Dimensions:", array3.shape)
print("No of elements in array:", array3.size)

My array: [1 2 3 4 5 6 7 8 9]
Type of array: <class 'numpy.ndarray'>
No of dimensions: 1
Array Dimensions: (9,)
No of elements in array: 9


In [ ]:
m = (1,2,3,4,5,6,7,8,9)
array4 = np.array(m)

In [ ]:
print("My array:", array4)
print("Type of array:", type(array4))
print("No of dimensions:",  array4.ndim)
print("Array Dimensions:", array4.shape)
print("No of elements in array:", array4.size)

My array: [1 2 3 4 5 6 7 8 9]
Type of array: <class 'numpy.ndarray'>
No of dimensions: 1
Array Dimensions: (9,)
No of elements in array: 9


arange


In [ ]:
arr_1 = np.arange(0,20)
print(arr_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr_2 = np.arange(0,20,2)
print(arr_2)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr_3 = np.arange(0,20,4)
print(arr_3)

[ 0  4  8 12 16]


In [ ]:
arr_4 = np.arange(4,20,5)
print(arr_4)

[ 4  9 14 19]


In [ ]:
arr_5 = np.arange(20)
print(arr_5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


    linspace()

In [ ]:
arr_1 = np.linspace(0,20)
print(arr_1)
print(arr_1.size)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
50


In [ ]:
arr_2 = np.linspace(0,20,2)
print(arr_2)

[ 0. 20.]


In [ ]:
arr_3 = np.linspace(0,20,6)
print(arr_3)

[ 0.  4.  8. 12. 16. 20.]


In [ ]:
arr_4 = np.linspace(10,20,50)
print(arr_4)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [ ]:
arr_5 = np.linspace(1,20)
print(arr_5)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


Zeros()


In [ ]:
arr_1 = np.zeros((3,3))
print(arr_1)
print("shape of array", arr_1.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape of array (3, 3)


In [ ]:
arr_2 = np.zeros(20)
print(arr_2)
print("shape of array", arr_2.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
shape of array (20,)


In [ ]:
#arr_3 = np.zeros(3,5)
print(arr_3)
print("shape of array", arr_3.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
shape of array (3, 5)


In [ ]:
arr_4 = np.zeros((3,3), dtype=int)
print(arr_4)
print("shape of array", arr_4.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
shape of array (3, 3)


ones()

In [ ]:
arr_1 = np.ones((3,3))
print(arr_1)
print("shape of array", arr_1.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape of array (3, 3)


In [ ]:
arr_1 = np.ones(50)
print(arr_1)
print("shape of array", arr_1.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
shape of array (50,)


In [ ]:
arr_4 = np.ones((3,3), dtype=int)
print(arr_4)
print("shape of array", arr_4.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
shape of array (3, 3)


eye()

In [ ]:
arr_1 = np.eye(3)
print(arr_1)
print("shape of array", arr_1.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape of array (3, 3)


In [ ]:
#arr_1 = np.eye((3,3))
print(arr_1)
print("shape of array", arr_1.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape of array (3, 3)


Matrix()

In [ ]:
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
print("shape of array", arr_1.shape)

[[1 2 3]
 [4 5 6]]
shape of array (2, 3)


In [ ]:
arr_2 = np.matrix([[1,2,3],[4,5,6]])
print(arr_2)
print("shape of array", arr_2.shape)

[[1 2 3]
 [4 5 6]]
shape of array (2, 3)


In [ ]:
arr_3 = np.array([1,2,3])
print(arr_3)
print("shape of array", arr_3.shape)

[1 2 3]
shape of array (3,)


In [ ]:
arr_4 = np.matrix([1,2,3])
print(arr_4)
print("shape of array", arr_4.shape)

[[1 2 3]]
shape of array (1, 3)


Max(),Min(),Argmax(),Argmin()

In [ ]:
arr_1 = np.array([11,44,2,6,33,7,8,9,33,4,5,6,22,8,9])
print(arr_1)

[11 44  2  6 33  7  8  9 33  4  5  6 22  8  9]


In [ ]:
print(np.max(arr_1))

44


In [ ]:
np.min(arr_1)

np.int64(2)

In [ ]:
np.argmax(arr_1)

np.int64(1)

In [ ]:
np.argmin(arr_1)

np.int64(2)

Reshape()


In [ ]:
array_1 = np.arange(1,21)
print("array:", array_1)
print("shape of array:", array_1.shape)
print("number of elements:", array_1.size)
print("number of dimension:", array_1.ndim)

array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape of array: (20,)
number of elements: 20
number of dimension: 1


In [ ]:
reshape_array = array_1.reshape(1,20)
print("array:", reshape_array)
print("shape of array:", reshape_array.shape)
print("number of elements:", reshape_array.size)
print("number of dimension:", reshape_array.ndim)

array: [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
shape of array: (1, 20)
number of elements: 20
number of dimension: 2


In [ ]:
reshape_array = array_1.reshape(20,1)
print("array:", reshape_array)
print("shape of array:", reshape_array.shape)
print("number of elements:", reshape_array.size)
print("number of dimension:", reshape_array.ndim)

array: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
shape of array: (20, 1)
number of elements: 20
number of dimension: 2


In [ ]:
reshape_array_2 = array_1.reshape(5,4)
print("array:", reshape_array_2)
print("shape of array:", reshape_array_2.shape)
print("number of elements:", reshape_array_2.size)
print("number of dimension:", reshape_array_2.ndim)

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
shape of array: (5, 4)
number of elements: 20
number of dimension: 2


In [ ]:
reshape_array_2 = array_1.reshape(4,5)
print("array:", reshape_array_2)
print("shape of array:", reshape_array_2.shape)
print("number of elements:", reshape_array_2.size)
print("number of dimension:", reshape_array_2.ndim)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
shape of array: (4, 5)
number of elements: 20
number of dimension: 2


Time Comparison between numpy array and list

In [ ]:
import time

In [ ]:
list_1 = list(range(10000000))
arr_1 = np.array(list_1)

In [ ]:
start_time = time.time()
result_list = [(x * 5) for x in list_1]
list_time = time.time() - start_time

In [ ]:
start_time = time.time()
result_array = arr_1 * 5
array_time = time.time() - start_time

In [ ]:
print("Time  taken by list:", list_time)
print("Time taken by array:", array_time)
print("Difference in time:", list_time - array_time)

Time  taken by list: 0.8921079635620117
Time taken by array: 0.046668291091918945
Difference in time: 0.8454396724700928


Outlier Detection


In [ ]:
data = np.array([22,3,44,55,66,77,44,66,22,33,88,4,999])
print(data)

[ 22   3  44  55  66  77  44  66  22  33  88   4 999]


In [ ]:
def Outlier_Detector(data):
  sorted(data)
  Q1, Q3 = np.percentile(data, [25,75])
  print("Q1:", Q1)
  print("Q3:", Q3)
  IQR = Q3 - Q1
  print("IQR:", IQR)
  lower_bound = Q1 - (1.5 * IQR)
  upper_bound = Q3 + (1.5 * IQR)
  return lower_bound, upper_bound

In [ ]:
lb, ub = Outlier_Detector(data)
print("The range is in between:", lb, "and", ub)

Q1: 22.0
Q3: 66.0
IQR: 44.0
The range is in between: -44.0 and 132.0


In [ ]:
outliers = [x for x in data if x < lb or x > ub]
print("Outliers in data:", outliers)

Outliers in data: [np.int64(999)]
